spring:
  datasource:
    # Use this for docker environment
    url: jdbc:postgresql://crave-postgres-container:5432/crave
    username: postgres
    password: crave
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect